############# English navigation ##############

# main menu
#[[main]]
#name = "Home"
#url = "/"
#weight = 1

[[main]]
name = "Software"
url = "/software"
weight = 2

[[main]]
name = "Data"
url = "/data"
weight = 3

[[main]]
name = "Ciberseguridad"
url = "/cybersecurity"
weight = 4

[[main]]
name = "Cloud"
url = "/cloud"
weight = 5

[[main]]
name = "AI"
url = "/ai"
weight = 6

[[main]]
name = "Networking"
url = "/networking"
weight = 7

# footer menu
#[[footer]]
#name = "Sobre nosotros"
#url = "/about"
#weight = 1

[[footer]]
name = "Condiciones generales"
url = "/terms"
weight = 1

[[footer]]
name = "Política de privacidad"
url = "/privacy-policy"
weight = 2
